# Use uma imagem base com o ambiente necessário, por exemplo, Ubuntu
FROM ubuntu:latest

# Instale as dependências necessárias
RUN apt-get update && \
  apt-get install -y g++ cmake

# Copie o código fonte do servidor para o container
COPY . /app

# Defina o diretório de trabalho
WORKDIR /app

# Compile o código do servidor
RUN g++ server.cpp -o server

# Exponha a porta em que o servidor irá escutar
EXPOSE 1303

# Comando para iniciar o servidor
CMD ["./server"]